version: "3"
services:
  nexus:
    container_name: nexus-rm
    image: registry-1.docker.io/sonatype/nexus3:3.60.0
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081" # HTTP Port to access Nexus RM web GUI
      - "8443:8443" # HTTPS Port to access Nexus RM web GUI
      - "8888:8888" # Custom port exposed for accessing Nexus RM Docker repository
    restart: unless-stopped
    stop_grace_period: 1m30s
volumes:
  nexus-data: